<a href="https://colab.research.google.com/github/hiuk21/new-project/blob/main/11%EC%A3%BC%EC%B0%A8_%ED%86%B5%EA%B3%84%EB%A1%9C%EC%9A%94%EC%95%BD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import gdown
gdown.download('https://bit.ly/3736JW1', 'ns_book6.csv', quiet = False)

Downloading...
From: https://bit.ly/3736JW1
To: /content/ns_book6.csv
100%|██████████| 55.0M/55.0M [00:00<00:00, 81.9MB/s]

'ns_book6.csv'

In [ ]:
import pandas as pd

ns_book6 = pd.read_csv('ns_book6.csv', low_memory=False)
ns_book6.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021.0,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021.0,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021.0,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021.0,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021.0,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19

기술 통계를 자동으로 추출해 주는 describe() 메서드

In [ ]:
ns_book6.describe()

                  번호           발행년도           도서권수           대출건수
count  379976.000000  379976.000000  379976.000000  379976.000000
mean   201726.332847    2008.516306       1.135874      11.504629
std    115836.454596       8.780529       0.483343      19.241926
min         1.000000    1947.000000       0.000000       0.000000
25%    102202.750000    2003.000000       1.000000       2.000000
50%    203179.500000    2009.000000       1.000000       6.000000
75%    301630.250000    2015.000000       1.000000      14.000000
max    401681.000000    2650.000000      40.000000    1765.000000

불리언 배열과 sum()함수를 활용하면 도서권수가 0인 도서의 행 개수 계산

In [ ]:
sum(ns_book6['도서권수'] == 0)

3206

0인 도서의 대출 데이터 제외

In [ ]:
ns_book6 = ns_book6[ns_book6['도서권수']>0]

describe() 메서드는 기본적으로 데이터 25%, 50%, 75%

원하는 위치 값 보고싶으면 percentiles 매개변수에 위치 지정

In [ ]:
ns_book6.describe(percentiles = [0.3, 0.6, 0.9])

                  번호           발행년도           도서권수           대출건수
count  376770.000000  376770.000000  376770.000000  376770.000000
mean   202977.476649    2008.460076       1.145540      11.593439
std    115298.245784       8.773148       0.473853      19.279409
min         1.000000    1947.000000       1.000000       0.000000
30%    124649.700000    2004.000000       1.000000       2.000000
50%    204550.500000    2009.000000       1.000000       6.000000
60%    243537.400000    2011.000000       1.000000       8.000000
90%    361341.100000    2018.000000       2.000000      28.000000
max    401681.000000    2650.000000      40.000000    1765.000000

수치가 아닌 다른 데이터 타입의 열의 시술통계를 보고 싶다면 include 매개변수에 데이터 타입을 지정

In [ ]:
ns_book6.describe(include = 'object')

,도서명,저자,출판사,ISBN,세트 ISBN,부가기호,권,주제분류번호,등록일자
count,376770,376770,376770,376770,55866,308252,61793,359792,376770
unique,336408,248850,21875,350810,14875,17,834,12467,4562
top,승정원일기,세종대왕기념사업회 [편],문학동네,9788937430299,9788937460005,0,1,813.6,1970-01-01
freq,250,303,4410,206,702,158235,13282,14816,28185

평균 구하기

range()는 하나의 숫자를 입력할 경우 0부터 입력된 숫자 직전까지 반복

In [ ]:
x = [10, 20, 30]
sum = 0
for i in range(3):
  sum += x[i]
print('평균', sum / len(x))

평균 20.0

In [ ]:
ns_book6['대출건수'].mean()

np.float64(11.593438968070707)

In [ ]:
ns_book6['대출건수'].median()

6.0

데이터 개수가 짝수이면 가운데 두 개의 값을 평균하여 중앙값 결정

In [ ]:
temp_df = pd.DataFrame([1,2,3,4])
temp_df.median()

0    2.5
dtype: float64

중복값 제거하고 중앙값 구하기
drop_duplicates() 메서드를 사용해 '대출건수' 열에서 중복된 값을 가진 행을 제거한 후 중앙값 계산

In [ ]:
ns_book6['대출건수'].drop_duplicates().median()

183.0

In [ ]:
ns_book6['대출건수'].min()

0

In [ ]:
ns_book6['대출건수'].max()

1765

quantile() 메서드
25% 위치 값 출력하려면 0.25

In [ ]:
ns_book6['대출건수'].quantile(0.25)

np.float64(2.0)

In [ ]:
ns_book6['대출건수'].quantile([0.25, 0.5, 0.75])

0.25     2.0
0.50     6.0
0.75    14.0
Name: 대출건수, dtype: float64

1,2,3,4,5 다섯 개의 숫자가 있을 때 90% 위치ㅔ 있는 것은

In [ ]:
pd.Series([1,2,3,4,5]).quantile(0.9)

np.float64(4.6)

*백분위*
대출건수 열의 값이 10보다 작은지 비교하여 불리언 배열 만들기

In [ ]:
borrow_10_flag = ns_book6['대출건수']< 10

borrow_10_flag 배열에서 mean() 메서들르 호출하여 평균을 구해 10보다 작은 값이 차지하는 비율 계산

In [ ]:
borrow_10_flag.mean()

np.float64(0.6402712530190833)

quantile()메서드에 백분위를 넣어 기대했던 10이 출력됨을 확인

In [ ]:
ns_book6['대출건수'].quantile(0.65)

np.float64(10.0)

var()메서드
대출건수 분산 구하기

In [ ]:
ns_book6['대출건수'].var()

371.6956304306922

std() 메서드
대출건수의 표준편차 계산

In [ ]:
ns_book6['대출건수'].std()

19.27940949382766

판다스의 std() 메서드를 수식으로 구현하려면 샘풀 개수를 n이 아니라 n-1로 나누어야 함
제곱근은 넘파이의 sqrt()함수를 사용하여 계산

In [ ]:
import numpy as np
diff = ns_book6['대출건수'] - ns_book6['대출건수'].mean()
np.sqrt(np.sum(diff**2)/(len(ns_book6)-1))

np.float64(19.279409493785508)

최빈값 구하기
mode() 메서드

In [ ]:
ns_book6['도서명'].mode()

0    승정원일기
Name: 도서명, dtype: object

In [ ]:
ns_book6['발행년도'].mode()

0    2012.0
Name: 발행년도, dtype: float64

데이터프레임에서 기술 통계 구하기
수치형 열만 연산할 수 있기 때문에 해당 열에만 적용되도록 numeric_only 매개변수를 true로 지정

In [ ]:
ns_book6.mean(numeric_only = True)

번호      202977.476649
발행년도      2008.460076
도서권수         1.145540
대출건수        11.593439
dtype: float64

loc메서드로 '도서명' 열부터 마지막 열까지애 대해 최빈값을 찾기

In [ ]:
ns_book6.loc[:,'도서명':].mode()

,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,승정원일기,세종대왕기념사업회 [편],문학동네,2012.0,9788937430299,9788937460005,0,1,813.6,1,0,1970-01-01

In [ ]:
ns_book6.to_csv('ns_book6.csv', index = False)

In [ ]:
import numpy as np
np.mean(ns_book6['대출건수'])

np.float64(11.593438968070707)

In [ ]:
np.average(ns_book6['대출건수'], weights = 1/ns_book6['도서권수'])

np.float64(10.543612175385386)

In [ ]:
np.mean(ns_book6['대출건수']/ ns_book6['도서권수'])

np.float64(9.873029861445774)

In [ ]:
ns_book6['대출건수'].sum()/ ns_book6['도서권수'].sum()

np.float64(10.120503701300958)

In [ ]:
np.median(ns_book6['대출건수'])

np.float64(6.0)

In [ ]:
np.min(ns_book6['대출건수'])

0

In [ ]:
np.max(ns_book6['대출건수'])

1765

In [ ]:
np.quantile(ns_book6['대출건수'], [0.25, 0.5, 0.75])

array([ 2.,  6., 14.])

In [ ]:
np.var(ns_book6['대출건수'])

371.694643898775

In [ ]:
ns_book6['대출건수'].var()

371.6956304306922

In [ ]:
ns_book6['대출건수'].var(ddof=0)

371.694643898775

In [ ]:
np.var(ns_book6['대출건수'], ddof=1)

371.6956304306922

In [ ]:
np.std(ns_book6['대출건수'])

19.279383908693113

unique 함수를 호출해 고유값(values)과 드장 회수 (counts) 배열 획득

In [ ]:
values, counts = np.unique(ns_book6['도서명'], return_counts=True)

argmax() 함수를 사용하여 counts 배열에서 가장 큰 값의 인덱스를 찾기

In [ ]:
max_idx = np.argmax(counts)

values 배열에서 해당 인덱스의 값 출력

In [ ]:
values[max_idx]

'승정원일기'